[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
bytemuck = { version = "1", features = ["derive", "min_const_generics"] }
crc32c = "0.6"
thiserror = "2"
io-uring = "0.7"
libc = "0.2"
uuid = { version = "1", features = ["v4"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
metrics = "0.24.6"
metrics-exporter-prometheus = "0.18.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }

# dev-dependencies
tempfile = "3"
assert_cmd = "2"
