[workspace]
members = [
    "plfsbdev",
    "plfschunkserver",
    "plfsclient",
    "plfscommon",
    "plfsgui",
    "plfsmaster",
    "plfsmetalogger",
    "plfsmount",
    "plfsnetdump",
]
exclude = ["vendor"]
resolver = "3"

[workspace.package]
version = "0.1.0"

[profile.dev]
overflow-checks = false

[profile.release]
lto = true
codegen-units = 1

[profile.release.package.plfsmount]
strip = "none"
debug = true
