[package]
name = "porfs-fuse"
description = "PolarisFS FUSE client v0: fuser::Filesystem implementation over porfs-mds"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
porfs-mds = { path = "../porfs-mds" }
fuser = "0.17"

[dev-dependencies]
tempfile.workspace = true
libc.workspace = true
porfs-rpc = { path = "../porfs-rpc" }
porfs-store = { path = "../porfs-store" }
tokio = { version = "1", features = ["rt-multi-thread", "net", "sync", "time"] }
