[package]
name = "mfsmaster"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2024"
autobins = false

[lib]
name = "mfsmaster"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "src/mfscommon/main.rs"
name = "mfsmaster"
[dependencies]
c2rust-bitfields = { path = "../vendor/c2rust-bitfields-0.22.1" }
libc = "0.2"
mfscommon = { path = "../mfscommon" }
