[package]
name = "porfs-mds"
description = "PolarisFS metadata server v0 (library): directory tree + inode table + file->extent map on redb + porfs-store"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
porfs-format = { path = "../porfs-format" }
porfs-store = { path = "../porfs-store" }
thiserror.workspace = true
redb = "4"
serde = { version = "1", features = ["derive"] }
bincode = "1"
twox-hash = "2"

[dev-dependencies]
tempfile.workspace = true
assert_cmd.workspace = true
