[package]
name = "plfs-common"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
bytes.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
