[workspace]
members = [
]
[package]
name = "mfschunkserver"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2024"
autobins = false

[lib]
name = "mfschunkserver"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "src/mfscommon/main.rs"
name = "main"
[dependencies]
c2rust-bitfields = { path = "../vendor/c2rust-bitfields-0.22.1" }
libc = "0.2"



[profile.release]
lto = true
codegen-units = 1
