[workspace]
members = [
]
[package]
name = "mfsmount"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2024"
autobins = false

[lib]
name = "mfsmount"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "src/fuse_client/mfsmount.rs"
name = "mfsmount"
[dependencies]
c2rust-bitfields = { path = "../vendor/c2rust-bitfields-0.22.1" }
libc = "0.2"
mfscommon = { path = "../mfscommon" }
mfsclient = { path = "../mfsclient" }



[profile.release]
lto = true
codegen-units = 1
strip = "none"
debug = true
