[package]
name = "porfs-cli"
description = "PolarisFS command line tool: mkfs / info / bench"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "porfs"
path = "src/main.rs"

[dependencies]
porfs-format = { path = "../porfs-format" }
porfs-store = { path = "../porfs-store" }
porfs-mds = { path = "../porfs-mds" }
porfs-fuse = { path = "../porfs-fuse" }
fuser = "0.17"
anyhow.workspace = true
clap.workspace = true
uuid.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
tempfile.workspace = true
