#!/usr/bin/env bash
# Generate docs/facts/dedup-map.md — md5 matrix of mfscommon/ and mfsclient/
# duplication across crates. Evidence for verified-claims VC-05 / VC-06.
set -euo pipefail
cd "$(dirname "$0")/.."

out=docs/facts/dedup-map.md
mkdir -p docs/facts
crates="mfsmaster mfschunkserver mfsmetalogger mfsmount mfsbdev mfsgui"

{
echo "# Dedup map — mfscommon/ and mfsclient/ duplication across crates"
echo
echo "Generated by \`tools/gen_dedup_map.sh\` on $(date -u +%Y-%m-%d) (repo $(git rev-parse --short HEAD))."
echo "Evidence for verified-claims VC-05 / VC-06. Regenerate after any re-transpile."
echo
echo "Legend: \`=\` byte-identical to the majority copy (md5 shown once per distinct hash),"
echo "\`A\`/\`B\`/\`C\`… distinct variants (same letter = same md5), \`-\` absent."
echo
echo "## mfscommon/"
echo
printf '| file |'
for c in $crates; do printf ' %s |' "$c"; done
echo
printf '| --- |'
for c in $crates; do printf ' --- |'; done
echo

files=$(for c in $crates; do ls "$c/src/mfscommon" 2>/dev/null; done | sort -u)
for f in $files; do
  declare -A h2l=(); li=0; letters=()
  for c in $crates; do
    p="$c/src/mfscommon/$f"
    if [ -f "$p" ]; then
      h=$(md5sum "$p" | cut -d' ' -f1)
      if [ -z "${h2l[$h]:-}" ]; then
        if [ $li -eq 0 ]; then h2l[$h]="="; else h2l[$h]=$(printf "\\$(printf '%03o' $((64+li)))"); fi
        li=$((li+1))
      fi
      letters+=("${h2l[$h]}")
    else
      letters+=("-")
    fi
  done
  printf '| %s |' "$f"
  for l in "${letters[@]}"; do printf ' %s |' "$l"; done
  echo
  unset h2l
done

echo
echo "## mfsclient/ (mfsmount vs mfsbdev)"
echo
echo '| file | mfsmount | mfsbdev |'
echo '| --- | --- | --- |'
files=$( (ls mfsmount/src/fuse_client; ls mfsbdev/src/mfsclient) | sort -u)
for f in $files; do
  a="mfsmount/src/fuse_client/$f"; b="mfsbdev/src/mfsclient/$f"
  if [ -f "$a" ] && [ -f "$b" ]; then
    if cmp -s "$a" "$b"; then row="| $f | = | = |"; else row="| $f | A | B |"; fi
  elif [ -f "$a" ]; then row="| $f | present | - |"
  else row="| $f | - | present |"; fi
  echo "$row"
done
} > "$out"
echo "wrote $out"
