#!/usr/bin/env bash
# Generate docs/facts/dedup-map.md — md5 matrix of plfscommon/ and plfsclient/
# duplication across crates. Evidence for verified-claims VC-05 / VC-06.
set -euo pipefail
cd "$(dirname "$0")/.."

out=docs/facts/dedup-map.md
mkdir -p docs/facts
crates="plfsmaster plfschunkserver plfsmetalogger plfsmount plfsbdev plfsgui"

{
echo "# Dedup map — plfscommon/ and plfsclient/ duplication across crates"
echo
echo "Generated by \`tools/gen_dedup_map.sh\` on $(date -u +%Y-%m-%d) (repo $(git rev-parse --short HEAD))."
echo "Evidence for verified-claims VC-05 / VC-06. Regenerate after any re-transpile."
echo
echo "Legend: \`=\` byte-identical to the majority copy (md5 shown once per distinct hash),"
echo "\`A\`/\`B\`/\`C\`… distinct variants (same letter = same md5), \`-\` absent."
echo
echo "## plfscommon/"
echo
echo '`plfscommon/src/` is authoritative shared source. Table below shows remaining'
echo 'per-daemon copies and their variants.'
echo
printf '| file |'
for c in $crates; do printf ' %s |' "$c"; done
echo
printf '| --- |'
for c in $crates; do printf ' --- |'; done
echo

files=$(for c in $crates; do ls "$c/src/plfscommon" 2>/dev/null; done | sort -u)
for f in $files; do
  declare -A h2l=(); li=0; letters=()
  for c in $crates; do
    p="$c/src/plfscommon/$f"
    if [ -f "$p" ]; then
      h=$(md5sum "$p" | cut -d' ' -f1)
      if [ -z "${h2l[$h]:-}" ]; then
        if [ $li -eq 0 ]; then h2l[$h]="="; else h2l[$h]=$(printf "\\$(printf '%03o' $((64+li)))"); fi
        li=$((li+1))
      fi
      letters+=("${h2l[$h]}")
    else
      letters+=("-")
    fi
  done
  printf '| %s |' "$f"
  for l in "${letters[@]}"; do printf ' %s |' "$l"; done
  echo
  unset h2l
done

echo
echo "## plfsclient/ (shared crate and frontend-specific modules)"
echo
echo '| file | shared plfsclient | plfsmount-only | plfsbdev-only |'
echo '| --- | --- | --- | --- |'
files=$( (ls plfsclient/src 2>/dev/null; ls plfsmount/src/fuse_client 2>/dev/null; ls plfsbdev/src/plfsclient 2>/dev/null) | sort -u)
for f in $files; do
  shared='-'; mount='-'; bdev='-'
  [ -f "plfsclient/src/$f" ] && shared='shared'
  [ -f "plfsmount/src/fuse_client/$f" ] && mount='present'
  [ -f "plfsbdev/src/plfsclient/$f" ] && bdev='present'
  printf '| %s | %s | %s | %s |\n' "$f" "$shared" "$mount" "$bdev"
done
} > "$out"
echo "wrote $out"
